In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([4,2,4])
arr

array([4, 2, 4])

In [4]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.full((5,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [7]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [8]:
# np.arange(300,30320,564)
np.arange(1,320,4)

array([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,
        53,  57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101,
       105, 109, 113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153,
       157, 161, 165, 169, 173, 177, 181, 185, 189, 193, 197, 201, 205,
       209, 213, 217, 221, 225, 229, 233, 237, 241, 245, 249, 253, 257,
       261, 265, 269, 273, 277, 281, 285, 289, 293, 297, 301, 305, 309,
       313, 317])

In [9]:
np.linspace(5,342,8)

array([  5.        ,  53.14285714, 101.28571429, 149.42857143,
       197.57142857, 245.71428571, 293.85714286, 342.        ])

In [10]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [11]:
myarr = np.array([[1,2,3],[4,5,2],[3,6,3],[8,4,23],[324,12,1]])

In [12]:
print(myarr.shape)

(5, 3)


In [13]:
myarr.size

15

In [14]:
myarr.ndim

2

In [15]:
myarr.dtype

dtype('int64')

In [16]:
myarr = np.array([[1,2,3],[4,5,2],[3,6,3],[8,4,23],[324,12,1]], dtype = 'float128')
myarr

array([[  1.,   2.,   3.],
       [  4.,   5.,   2.],
       [  3.,   6.,   3.],
       [  8.,   4.,  23.],
       [324.,  12.,   1.]], dtype=float128)

In [17]:
n = myarr.astype('float64')
n.dtype

dtype('float64')

In [18]:
myarr.dtype

dtype('float128')

In [27]:
myarr = np.array([[1,2,3],[4,5,2],[3,6,3],[8,4,23],[324,12,1]])

In [28]:
reshaped = myarr.reshape((3,5))

In [29]:
reshaped

array([[  1,   2,   3,   4,   5],
       [  2,   3,   6,   3,   8],
       [  4,  23, 324,  12,   1]])

In [30]:
myarr

array([[  1,   2,   3],
       [  4,   5,   2],
       [  3,   6,   3],
       [  8,   4,  23],
       [324,  12,   1]])

In [32]:
myarr.flatten()

array([  1,   2,   3,   4,   5,   2,   3,   6,   3,   8,   4,  23, 324,
        12,   1])