In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,2],[3,6,3],[8,4,23],[324,12,1]])

In [ ]:
print(arr)

[[  1   2   3]
 [  4   5   2]
 [  3   6   3]
 [  8   4  23]
 [324  12   1]]


In [4]:
flat = arr.flatten()
flat

array([  1,   2,   3,   4,   5,   2,   3,   6,   3,   8,   4,  23, 324,
        12,   1])

In [5]:
print(flat[0])
print(flat[:6])
print(flat[3:7])
print(flat[::3])

1
[1 2 3 4 5 2]
[4 5 2 3]
[  1   4   3   8 324]


In [6]:
# b = flat[3:9]
b = flat[3:9].copy()
b

array([4, 5, 2, 3, 6, 3])

In [7]:
b[2] = 345353
b

array([     4,      5, 345353,      3,      6,      3])

In [8]:
flat

array([  1,   2,   3,   4,   5,   2,   3,   6,   3,   8,   4,  23, 324,
        12,   1])

In [16]:
arr = np.array([1,2,3,4,5,2,3,6,3,8,4,23,324,12,1])
arr[[3,6,12]]

array([  4,   3, 324])

In [14]:
arr[arr>5]

array([  6,   8,  23, 324,  12])